Update diagramas MMTY
Vatmex/mexico-vatsys-sector pull request #132
Opened 2022-06-12 01:17 UTC by enriquea88

Corrección de diagramas y adicionales

2022-06-20 04:12 UTC, gvaldezsan requested changes
Arreglar temas de estilo

2022-06-20 04:12 UTC, gvaldezsan commented on Maps/TMA Ciudad Victoria/ASMGCS_MMCV.xml
> +      <Point Name="C">+234242.700-0985730.030</Point>
Si bien correcto no sigue Coding style de orden alfabetico

2022-06-20 05:38 UTC, enriquea88 commented
Se corrige orden alfabético

2022-07-06 04:44 UTC, gvaldezsan approved these changes

2022-07-06 04:44 UTC, merged